# Generated by Django 5.1.1 on 2024-09-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_table', '0002_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
