# Generated by Django 5.1.1 on 2024-10-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score_table', '0005_fujitaranking_participant_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fujitaranking',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fujitaranking',
            old_name='participant',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='created_date',
            new_name='posted_date',
        ),
    ]
