# Generated by Django 5.1.1 on 2024-10-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_table', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_not_there',
            field=models.BooleanField(default=False),
        ),
    ]
